# This file provides build and deploy instructions to Netlify.

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # This tells Netlify's bundler to NOT bundle these packages.
  # It forces them to be installed normally in the cloud, fixing the bug.
  external_node_modules = ["axios", "@supabase/supabase-js"]